# A custom workflow that checks the validity of
# URLs in source code as well as documentation.
on:
  push:
    branches:
      - main
      - devel
      - pre-release
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - devel
      - pre-release
  workflow_dispatch:
  # Allow for workflow inheritance
  workflow_call:

concurrency:
  group: links-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
name: urlchecker

jobs:
  urlchecker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::urlchecker

      - name: Check for valid URLs
        run: |
          urlchecker::url_check(
            path = ".",
            db = NULL,
            parallel = TRUE,
            pool = curl::new_pool(),
            progress = TRUE
          )
        shell: Rscript {0}
