# A custom workflow that checks the validity of
# URLs in source code as well as documentation.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: urlchecker

jobs:
  urlchecker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::urlchecker

      - name: Test coverage
        run: |
          urlchecker::url_check(
            path = ".",
            db = NULL,
            parallel = TRUE,
            pool = curl::new_pool(),
            progress = TRUE
          )
        shell: Rscript {0}
